http:
  port: 8088 ## 运行端口
  runMode: debug  ## 运行模式 debug,dev,test,release
  url: 127.0.0.1

db:
  dialect: mysql
  url: 139.224.208.254
  port: 3306
  database: devops
  user: mackie
  password: mackie,

redis:
  url: 127.0.0.1
  port: 6379
  db: 1
  password: 123456

session:

log:
  output: stdout # stdout file
  level: debug # debug dev test release
