http:
  port: 8088 ## 运行端口
  runMode: debug  ## 运行模式 debug,dev,test,release

db:
  dialect: mysql
  url: http://127.0.0.1
  port: 3306
  database: test
  user: root
  password: 123456

redis:
  url: http://127.0.0.1
  port: 6379
  db: 1
  password: 123456

session:

log:
  output: stdout # stdout file
  level: debug # debug dev test release
